### ISSUE TITLE
ASM:network gateway vnet diagnostics stop not working

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#257]
network gateway vnet diagnostics stop not working
<pre>
<code>
C:\June\2june\azure-xplat-cli-dev-asm-network>node bin/azure network gateway vnet diagnostics stop vnet1 -vv
info:    Executing command network gateway vnet diagnostics stop
verbose: Stopping diagnostics session in a virtual network "vnet1"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'PUT',
silly:       headers: {
silly:           Content-Type: 'application/xml',
silly:           x-ms-version: '2014-10-01',
silly:           Content-Length: 138,
silly:           user-agent: 'WindowsAzureXplatCLI/0.9.2'
silly:       },
silly:       url: 'https://management.core.windows.net/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/services/networking/vnet1/gateway/publicdiagnostics',
silly:       body: '<?xml version="1.0" encoding="utf-8" standalone="yes"?><UpdateGatewayPublicDiagnostics xmlns="http://schemas.microsoft.com/windowsazure"/>'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 400,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           content-length: '275',
silly:           content-type: 'application/xml; charset=utf-8',
silly:           server: '1.0.6198.235 (rd_rdfe_stable.150528-1357) Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0',
silly:           x-ms-servedbyregion: 'usnorth2',
silly:           x-ms-request-id: '1ffdd273892aa75a8a51bf877e92401a',
silly:           date: 'Wed, 03 Jun 2015 14:25:33 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: '<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>BadRequest</Code><Message>The s
pecified CustomerStorageName was not valid. It should be the name of a storage account that you have access to.</Message></Error>'
silly:   }
error:   The specified CustomerStorageName was not valid. It should be the name of a storage account that you have access to.
silly:   {
silly:       stack: 'Error: The specified CustomerStorageName was not valid. It should be the name of a storage account that you have access to.\n  <<< async stack >>
>\n  at stopVpnDiagnosticsSession__15 (C:\\June\\2june\\azure-xplat-cli-dev-asm-network\\lib\\commands\\asm\\network\\vpnGateway._js:305:55)\n  at stopVpnDiagnosticsS
ession__46 (C:\\June\\2june\\azure-xplat-cli-dev-asm-network\\lib\\commands\\asm\\network\\networkClient._js:313:16)\n  at __40 (C:\\June\\2june\\azure-xplat-cli-dev-
asm-network\\lib\\commands\\asm\\network._js:763:21)\n  <<< raw stack >>>\n    at Function.ServiceClient._normalizeError (C:\\June\\2june\\azure-xplat-cli-dev-asm-net
work\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\services\\serviceclient.js:815:23)\n    at C:\\June\\2june\\azure-xplat-cli-dev-asm-network\\nod
e_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\services\\filters\\errorhandlingfilter.js:44:29\n    at Request._callback (C:\\June\\2june\\azure-xplat-c
li-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\http\\request-pipeline.js:109:14)\n    at Request.self.callback (C:\\June\\2june\\
azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\node_modules\\request\\request.js:199:22)\n    at Request.emit (events.js:
110:17)\n    at Request.<anonymous> (C:\\June\\2june\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\node_modules\\reques
t\\request.js:1160:14)\n    at Request.emit (events.js:129:20)\n    at IncomingMessage.<anonymous> (C:\\June\\2june\\azure-xplat-cli-dev-asm-network\\node_modules\\az
ure-mgmt-vnet\\node_modules\\azure-common\\node_modules\\request\\request.js:1111:12)\n    at IncomingMessage.emit (events.js:129:20)\n    at _stream_readable.js:908:
16\n',
silly:       message: 'The specified CustomerStorageName was not valid. It should be the name of a storage account that you have access to.',
silly:       code: 'BadRequest',
silly:       statusCode: 400,
silly:       requestId: '1ffdd273892aa75a8a51bf877e92401a',
silly:       __frame: {
silly:           name: 'stopVpnDiagnosticsSession__15',
silly:           line: 301,
silly:           file: 'C:\\June\\2june\\azure-xplat-cli-dev-asm-network\\lib\\commands\\asm\\network\\vpnGateway._js',
silly:           prev: {
silly:               name: 'stopVpnDiagnosticsSession__46',
silly:               line: 309,
silly:               file: 'C:\\June\\2june\\azure-xplat-cli-dev-asm-network\\lib\\commands\\asm\\network\\networkClient._js',
silly:               prev: {
silly:                   name: '__40',
silly:                   line: 759,
silly:                   file: 'C:\\June\\2june\\azure-xplat-cli-dev-asm-network\\lib\\commands\\asm\\network._js',
silly:                   prev: undefined,
silly:                   calls: 2,
silly:                   active: false,
silly:                   offset: 4,
silly:                   col: 20
silly:               },
silly:               calls: 1,
silly:               active: false,
silly:               offset: 4,
silly:               col: 15
silly:           },
silly:           calls: 0,
silly:           active: false,
silly:           offset: 4,
silly:           col: 54
silly:       },
silly:       rawStack: 'Error: The specified CustomerStorageName was not valid. It should be the name of a storage account that you have access to.\n    at Function.S
erviceClient._normalizeError (C:\\June\\2june\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\services\\serviceclien
t.js:815:23)\n    at C:\\June\\2june\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\services\\filters\\errorhandlin
gfilter.js:44:29\n    at Request._callback (C:\\June\\2june\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\http\\re
quest-pipeline.js:109:14)\n    at Request.self.callback (C:\\June\\2june\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\
node_modules\\request\\request.js:199:22)\n    at Request.emit (events.js:110:17)\n    at Request.<anonymous> (C:\\June\\2june\\azure-xplat-cli-dev-asm-network\\node_
modules\\azure-mgmt-vnet\\node_modules\\azure-common\\node_modules\\request\\request.js:1160:14)\n    at Request.emit (events.js:129:20)\n    at IncomingMessage.<anon
ymous> (C:\\June\\2june\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\node_modules\\request\\request.js:1111:12)\n    a
t IncomingMessage.emit (events.js:129:20)\n    at _stream_readable.js:908:16\n'
silly:   }
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
verbose: Error: The specified CustomerStorageName was not valid. It should be the name of a storage account that you have access to.
  <<< async stack >>>
  at stopVpnDiagnosticsSession__15 (C:\June\2june\azure-xplat-cli-dev-asm-network\lib\commands\asm\network\vpnGateway._js:305:55)
  at stopVpnDiagnosticsSession__46 (C:\June\2june\azure-xplat-cli-dev-asm-network\lib\commands\asm\network\networkClient._js:313:16)
  at __40 (C:\June\2june\azure-xplat-cli-dev-asm-network\lib\commands\asm\network._js:763:21)
  <<< raw stack >>>
    at Function.ServiceClient._normalizeError (C:\June\2june\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\lib\services\servi
ceclient.js:815:23)
    at C:\June\2june\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\lib\services\filters\errorhandlingfilter.js:44:29
    at Request._callback (C:\June\2june\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\lib\http\request-pipeline.js:109:14)
    at Request.self.callback (C:\June\2june\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\node_modules\request\request.js:199
:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (C:\June\2june\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\node_modules\request\request.js:1160:
14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (C:\June\2june\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\node_modules\request\request.
js:1111:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16

error:   network gateway vnet diagnostics stop command failed

</code>
</pre>

**Comment by roman-boltunov** [comment]
Hi @HimanshuBri, did you start diagnostics session before stopping it?

**Comment by HimanshuBri** [comment]
@roman-boltunov. Yes

**Comment by roman-boltunov** [comment]
@HimanshuBri then which storage did you use? Did you create it, or was it created before?

**Comment by HimanshuBri** [comment]
@roman-boltunov. It was created before.

**Comment by roman-boltunov** [comment]
@HimanshuBri could you please try to create it yourself, so we can actually see that error depends on it.

**Comment by roman-boltunov** [comment]
@HimanshuBri I think server response is clear enough for the end user. If you have no access to the storage, so you can't work with it.

**Comment by roman-boltunov** [comment]
@HimanshuBri any updates on this? Have you tried to create storage yourself and then execute diagnostics start and stop specifying created storage?

**Comment by HimanshuBri** [comment]
@roman-boltunov. I will tell you the steps that i followed:-
First of all i created a storage account just now. Then started the diagnostics then tried to run the stop command, got the same error.
Here is the screenshot for the same.
![image](https://cloud.githubusercontent.com/assets/10084788/8056218/8af0f2e2-0ec3-11e5-8137-564e0b370483.png)

**Comment by roman-boltunov** [comment]
@HimanshuBri thank you, I verified it and found defect which raises that behavior. It's fixed now, could you please retest it?

**Comment by HimanshuBri** [comment]
@roman-boltunov. Getting below mentioned error now.
![image](https://cloud.githubusercontent.com/assets/10084788/8056789/2e4d9300-0ec9-11e5-93f4-1270564c34f6.png)

**Comment by roman-boltunov** [comment]
@HimanshuBri you should start diagnostics session first

**Comment by roman-boltunov** [comment]
@HimanshuBri please try following steps:
1. start diagnostics session for about 300 seconds.
2. try to stop diagnostics session in that period of time.

**Comment by HimanshuBri** [comment]
@roman-boltunov. Thanks. Will try above steps.

**Comment by roman-boltunov** [comment]
@HimanshuBri any updates on this?

**Comment by HimanshuBri** [comment]
@roman-boltunov. Tried it, was getting some internal server error. Will test it once again and let you know the outcome.

**Comment by roman-boltunov** [comment]
@HimanshuBri thank you.

**Comment by HimanshuBri** [comment]
@roman-boltunov  yes its working.Thanks. But do we need to give duration as 300 seconds only?

**Comment by roman-boltunov** [comment]
@HimanshuBri no, we set 300 seconds just to have enough time to try to stop diagnostics.

**Comment by HimanshuBri** [comment]
@roman-boltunov. Thanks for the confirmation. Working fine.

**Comment by HimanshuBri** [comment]
@roman-boltunov. Please find the attached screenshot. Not working for small duration like 30.
![image](https://cloud.githubusercontent.com/assets/10084788/8227944/aee2306a-15c8-11e5-8dd0-040da9d3a5af.png)

**Comment by roman-boltunov** [comment]
@HimanshuBri thank you, will investigate it.

**Comment by roman-boltunov** [comment]
@HimanshuBri tried this, when we execute this command it takes about ~35 seconds to response, but diagnostics session starts immediately, so the minimal duration we can specify is about 40 seconds and it will work(with this amount of time) only if we will try to stop diagnostics session immediately after start. I think these are all expected, there no issue.

**Comment by HimanshuBri** [comment]
@roman-boltunov. Working for 50 seconds and above, but failing for values below that. Please check the attached screenshot.
![image](https://cloud.githubusercontent.com/assets/10084788/8281207/12ba4cca-1903-11e5-8888-b81653a440a4.png)

**Comment by roman-boltunov** [comment]
@HimanshuBri thanks for testing.
Adding @anuchandy, please refer our last two comments. Is it expected and OK, or should we report this? Could you please share your thoughts?

**Comment by anuchandy** [comment]
Is this the correct repo step:

If we start diagnostics session for a duration less than 50 sec then stopping such session throws the error "The current gateway public diagnostics state does not allow stopping an existing public diagnosis session". For all duration > 50 sec, stop won't throw error.

**Comment by roman-boltunov** [comment]
@anuchandy yes, that's true, but only if we have enough time to stop diagnostics session. I think 45 seconds is the lowest duration. I personally think this is not an issue. For 'start' command it takes about ~40 seconds to response. So, even if diagnostics session starts before server responses, still diagnostics session works as expected.
