### ISSUE TITLE
ASM: 'network application-gateway address-pool add' working with wrong IP Address

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#317]
Please find the attached screenshots.
![image](https://cloud.githubusercontent.com/assets/10084788/8106064/e7dde61a-105b-11e5-8686-41e6b179d3d2.png)

Also working when specifying same IP address more than once.
![image](https://cloud.githubusercontent.com/assets/10084788/8106177/c0a1a7a2-105c-11e5-9896-fb8780697a9e.png)

**Comment by romangromov** [comment]
@HimanshuBri added validation, please make sure all is fine

**Comment by romangromov** [comment]
@anuchandy server allows us to create an backend address pool with ip address duplicates, so we need to inform Kapil about this issue and mark it as `external`, please confirm

**Comment by romangromov** [comment]
@HimanshuBri I've reported duplicates issue to Kapil, will keep you informed about this, stay tuned

**Comment by HimanshuBri** [comment]
@romangromov. Thanks. Can you please check below error screenshot.
![image](https://cloud.githubusercontent.com/assets/10084788/8106713/6fa90142-1061-11e5-8742-7e4890302492.png)

**Comment by anuchandy** [comment]
@romangromov let us not add any validation that server suppose to do. @HimanshuBri  we reported this to server team.

**Comment by HimanshuBri** [comment]
@anuchandy. Thanks.

**Comment by romangromov** [comment]
@HimanshuBri UPD: I've added validation for DNS name, now it should support IPv4 or DNS name as bakend pool address. Let's wait response from Kapil about duplicates issue

**Comment by HimanshuBri** [comment]
@romangromov. Getting error in address-pool add. Please see the code snippet. <code><pre>
E:\4486\15-June-2015\azure-xplat-cli-dev-asm-network>node bin/azure network application-gateway address-pool add Testappgate Testaddpool -vv
info:    Executing command network application-gateway address-pool add
List of IP addresses or DNS names: 10.10.10.10
verbose: Getting configuration for an application gateway "Testappgate"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { x-ms-version: '2014-10-01', user-agent: 'WindowsAzureXplatCLI/0.9.2' },
silly:       url: 'https://management.core.windows.net/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/services/appgwprodnext/ApplicationGateways/Testappgate/configuration?api-version=1.0'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 200,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           transfer-encoding: 'chunked',
silly:           server: '1.0.6198.240 (rd_rdfe_stable.150608-1900) Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0',
silly:           x-ms-servedbyregion: 'usnorth2',
silly:           x-ms-request-id: '3315a6f7f881b012805fec0f2b25f946',
silly:           date: 'Mon, 15 Jun 2015 10:38:00 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: ''
silly:   }
verbose: Setting configuration for an application gateway "Testappgate"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'POST',
silly:       headers: {
silly:           Content-Type: 'application/xml',
silly:           x-ms-version: '2014-10-01',
silly:           Content-Length: 451,
silly:           user-agent: 'WindowsAzureXplatCLI/0.9.2'
silly:       },
silly:       url: 'https://management.core.windows.net/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/services/appgwprodnext/ApplicationGateways/Testappgate/configuration?api-version=1.0',
silly:       body: '<?xml version="1.0" encoding="utf-8" standalone="yes"?><ApplicationGatewayConfiguration xmlns="http://schemas.microsoft.com/windowsazure"><FrontendIPConfigurations/><FrontendPorts/><BackendAddressPools><BackendAddressPool><Name>Testaddpool</Name><IPAddresses><IPAddress>10.10.10.10</IPAddress></IPAddresses></BackendAddressPool></BackendAddressPools><BackendHttpSettingsList/><HttpListeners/><HttpLoadBalancingRules/></ApplicationGatewayConfiguration>'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 500,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           content-length: '229',
silly:           content-type: 'application/xml; charset=utf-8',
silly:           server: '1.0.6198.240 (rd_rdfe_stable.150608-1900) Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0',
silly:           x-ms-servedbyregion: 'usnorth2',
silly:           x-ms-request-id: 'b34dc7c50d73b425b9e5517874acdf63',
silly:           date: 'Mon, 15 Jun 2015 10:38:05 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: '<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>InternalError</Code><Message>The server encountered an internal error. Please retry the request.</Message></Error>'
silly:   }
error:   The server encountered an internal error. Please retry the request.
silly:   {
silly:       stack: 'Error: The server encountered an internal error. Please retry the request.\n    at Function.ServiceClient._normalizeError (E:\\4486\\15-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\services\\serviceclient.js:815:23)\n    at E:\\4486\\15-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\services\\filters\\errorhandlingfilter.js:44:29\n    at Request._callba
ck (E:\\4486\\15-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\http\\request-pipeline.js:109:14)\n    at Request.self.callback (E:\\4486\\15-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\node_modules\\request\\request.js:199:22)\n    at Request.emit (events.js:110:17)\n    at Request.<anonymous> (E:\\4486\\15-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-v
net\\node_modules\\azure-common\\node_modules\\request\\request.js:1160:14)\n    at Request.emit (events.js:129:20)\n    at IncomingMessage.<anonymous> (E:\\4486\\15-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\node_modules\\request\\request.js:1111:12)\n    at IncomingMessage.emit (events.js:129:20)\n    at _stream_readable.js:908:16\n',
silly:       message: 'The server encountered an internal error. Please retry the request.',
silly:       code: 'InternalError',
silly:       statusCode: 500,
silly:       requestId: 'b34dc7c50d73b425b9e5517874acdf63',
silly:       __frame: {
silly:           name: 'setConfig__13',
silly:           line: 288,
silly:           file: 'E:\\4486\\15-June-2015\\azure-xplat-cli-dev-asm-network\\lib\\commands\\asm\\network\\appGateway._js',
silly:           prev: {
silly:               name: 'addBackendAddressPool__14',
silly:               line: 298,
silly:               file: 'E:\\4486\\15-June-2015\\azure-xplat-cli-dev-asm-network\\lib\\commands\\asm\\network\\appGateway._js',
silly:               prev: {
silly:                   name: 'addAddressPoolForApplicationGateway__58',
silly:                   line: 382,
silly:                   file: 'E:\\4486\\15-June-2015\\azure-xplat-cli-dev-asm-network\\lib\\commands\\asm\\network\\networkClient._js',
silly:                   prev: {
silly:                       name: '__58',
silly:                       line: 1022,
silly:                       file: 'E:\\4486\\15-June-2015\\azure-xplat-cli-dev-asm-network\\lib\\commands\\asm\\network._js',
silly:                       prev: undefined,
silly:                       calls: 4,
silly:                       active: false,
silly:                       offset: 6,
silly:                       col: 20
silly:                   },
silly:                   calls: 1,
silly:                   active: false,
silly:                   offset: 3,
silly:                   col: 15
silly:               },
silly:               calls: 2,
silly:               active: false,
silly:               offset: 14,
silly:               col: 13
silly:           },
silly:           calls: 0,
silly:           active: false,
silly:           offset: 3,
silly:           col: 55
silly:       },
silly:       rawStack: 'Error: The server encountered an internal error. Please retry the request.\n    at Function.ServiceClient._normalizeError (E:\\4486\\15-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\services\\serviceclient.js:815:23)\n    at E:\\4486\\15-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\services\\filters\\errorhandlingfilter.js:44:29\n    at Request._cal
lback (E:\\4486\\15-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\http\\request-pipeline.js:109:14)\n    at Request.self.callback (E:\\4486\\15-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\node_modules\\request\\request.js:199:22)\n    at Request.emit (events.js:110:17)\n    at Request.<anonymous> (E:\\4486\\15-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgm
t-vnet\\node_modules\\azure-common\\node_modules\\request\\request.js:1160:14)\n    at Request.emit (events.js:129:20)\n    at IncomingMessage.<anonymous> (E:\\4486\\15-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\node_modules\\request\\request.js:1111:12)\n    at IncomingMessage.emit (events.js:129:20)\n    at _stream_readable.js:908:16\n'
silly:   }
info:    Error information has been recorded to C:\Users\himanshu.agarwal\.azure\azure.err
verbose: Error: The server encountered an internal error. Please retry the request.
    at Function.ServiceClient._normalizeError (E:\4486\15-June-2015\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\lib\services\serviceclient.js:815:23)
    at E:\4486\15-June-2015\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\lib\services\filters\errorhandlingfilter.js:44:29
    at Request._callback (E:\4486\15-June-2015\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\lib\http\request-pipeline.js:109:14)
    at Request.self.callback (E:\4486\15-June-2015\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\node_modules\request\request.js:199:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (E:\4486\15-June-2015\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\node_modules\request\request.js:1160:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (E:\4486\15-June-2015\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\node_modules\request\request.js:1111:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16

error:   network application-gateway address-pool add command failed


E:\4486\15-June-2015\azure-xplat-cli-dev-asm-network></pre></code>

**Comment by romangromov** [comment]
@HimanshuBri we need to set a non-empty configuration for an existing application gateway at first before making any change (add or remove something) related to configuration - this is by design on server side. Please, run `azure network application-gateway config import` at first, referencing comment with JSON config https://github.com/MSOpenTech/azure-xplat-cli/issues/286#issuecomment-109964863

**Comment by HimanshuBri** [comment]
@romangromov. Thanks.

**Comment by romangromov** [comment]
@HimanshuBri hi again, could you please check this issue and close if all is ok? Thank you in advance!

**Comment by HimanshuBri** [comment]
@romangromov. Hi, i don't think if we can close, as if you through above comments of @anuchandy, this has been reported to server team.

**Comment by romangromov** [comment]
UPD: issue still exist on server side
