### ISSUE TITLE
ASM: 'network gateway vnet shared-key set' not working

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#320]
Please find attached code snippet.<code><pre>E:\4486\11-June-2015\azure-xplat-cli-dev-asm-network>node bin/azure network gateway vnet shared-key set vnet abcd -t Testlocnet -vv
info:    Executing command network gateway vnet shared-key set
verbose: Setting up shared key for vnet "vnet"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'POST',
silly:       headers: {
silly:           Content-Type: 'application/xml',
silly:           x-ms-version: '2014-10-01',
silly:           Content-Length: 147,
silly:           user-agent: 'WindowsAzureXplatCLI/0.9.2'
silly:       },
silly:       url: 'https://management.core.windows.net/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/services/networking/vnet/gateway/connection/Testlocnet/sharedkey',
silly:       body: '<?xml version="1.0" encoding="utf-8" standalone="yes"?><SharedKey xmlns="http://schemas.microsoft.com/windowsazure"><Value>abcd</Value></SharedKey>'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 202,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           content-length: '210',
silly:           content-type: 'application/xml; charset=utf-8',
silly:           server: '1.0.6198.240 (rd_rdfe_stable.150608-1900) Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0',
silly:           x-ms-servedbyregion: 'usnorth2',
silly:           x-ms-request-id: '0f29afc953daab128599bc8fbe76e455',
silly:           date: 'Thu, 11 Jun 2015 12:40:03 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: '<GatewayOperationAsyncResponse xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><ID>1cca9938-74df-446c-876f-f6a1f7609eb8</ID></GatewayOperationAsyncResponse>'
silly:   }
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { x-ms-version: '2014-10-01', user-agent: 'WindowsAzureXplatCLI/0.9.2' },
silly:       url: 'https://management.core.windows.net/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/services/networking/operation/1cca9938-74df-446c-876f-f6a1f7609eb8'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 200,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           content-length: '550',
silly:           content-type: 'application/xml; charset=utf-8',
silly:           server: '1.0.6198.240 (rd_rdfe_stable.150608-1900) Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0',
silly:           x-ms-servedbyregion: 'usnorth2',
silly:           x-ms-request-id: '259c2cf5e2a5a4c688d4a8b36a5f3825',
silly:           date: 'Thu, 11 Jun 2015 12:40:34 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: '<GatewayOperation xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Data/><Error><Code>InternalError</Code><Message>An internal error has occurred.</Message></Error><HttpStatusCode>InternalServerError</HttpStatusCode><ID>1cca9938-74df-446c-876f-f6a1f7609eb8</ID><OperationCompletedTime>2015-06-11T12:40:03.7581609</OperationCompletedTime><OperationName>ResetSharedKey</OperationName><OperationStartedTime>2015-06-11T12:40:02.21
39504</OperationStartedTime><Status>Failed</Status></GatewayOperation>'
silly:   }
error:   InternalError : An internal error has occurred.
silly:   {
silly:       stack: 'Error: InternalError : An internal error has occurred.\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\lib\\networkManagementClient.js:6878:30\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\lib\\networkManagementClient.js:6004:14\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\lib\\util\\utils.js:326:7\n    at handleRedirect (E:\\4486\\11-June-2015\\azure-xplat-c
li-dev-asm-network\\lib\\util\\utils.js:303:9)\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\lib\\util\\logging.js:281:7\n    at handleRedirect (E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\services\\filters\\redirectfilter.js:36:9)\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\services\\filters\\errorhandlingfilter.js:4
9:7\n    at Request._callback (E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\http\\request-pipeline.js:109:14)\n    at Request.self.callback (E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\node_modules\\request\\request.js:199:22)\n    at Request.emit (events.js:110:17)\n',
silly:       message: 'InternalError : An internal error has occurred.',
silly:       error: { stack: 'Error: An internal error has occurred.\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\lib\\networkManagementClient.js:6879:32\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\lib\\networkManagementClient.js:6004:14\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\lib\\util\\utils.js:326:7\n    at handleRedirect (E:\\4486\\11-June-2015\\azure-xplat-cli-dev-
asm-network\\lib\\util\\utils.js:303:9)\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\lib\\util\\logging.js:281:7\n    at handleRedirect (E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\services\\filters\\redirectfilter.js:36:9)\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\services\\filters\\errorhandlingfilter.js:49:7\n
  at Request._callback (E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\http\\request-pipeline.js:109:14)\n    at Request.self.callback (E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\node_modules\\request\\request.js:199:22)\n    at Request.emit (events.js:110:17)\n', code: 'InternalError', message: 'An internal error has occurred.' },
silly:       __frame: {
silly:           name: 'setSharedKey__10',
silly:           line: 217,
silly:           file: 'E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\lib\\commands\\asm\\network\\vpnGateway._js',
silly:           prev: {
silly:               name: 'setSharedKey__41',
silly:               line: 275,
silly:               file: 'E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\lib\\commands\\asm\\network\\networkClient._js',
silly:               prev: {
silly:                   name: '__34',
silly:                   line: 664,
silly:                   file: 'E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\lib\\commands\\asm\\network._js',
silly:                   prev: undefined,
silly:                   calls: 3,
silly:                   active: false,
silly:                   offset: 5,
silly:                   col: 20
silly:               },
silly:               calls: 1,
silly:               active: false,
silly:               offset: 4,
silly:               col: 15
silly:           },
silly:           calls: 1,
silly:           active: false,
silly:           offset: 7,
silly:           col: 44
silly:       },
silly:       rawStack: 'Error: InternalError : An internal error has occurred.\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\lib\\networkManagementClient.js:6878:30\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\lib\\networkManagementClient.js:6004:14\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\lib\\util\\utils.js:326:7\n    at handleRedirect (E:\\4486\\11-June-2015\\azure-xpla
t-cli-dev-asm-network\\lib\\util\\utils.js:303:9)\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\lib\\util\\logging.js:281:7\n    at handleRedirect (E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\services\\filters\\redirectfilter.js:36:9)\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\services\\filters\\errorhandlingfilter.j
s:49:7\n    at Request._callback (E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\http\\request-pipeline.js:109:14)\n    at Request.self.callback (E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\node_modules\\request\\request.js:199:22)\n    at Request.emit (events.js:110:17)\n'
silly:   }
info:    Error information has been recorded to C:\Users\himanshu.agarwal\.azure\azure.err
verbose: Error: InternalError : An internal error has occurred.
    at E:\4486\11-June-2015\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\lib\networkManagementClient.js:6878:30
    at E:\4486\11-June-2015\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\lib\networkManagementClient.js:6004:14
    at E:\4486\11-June-2015\azure-xplat-cli-dev-asm-network\lib\util\utils.js:326:7
    at handleRedirect (E:\4486\11-June-2015\azure-xplat-cli-dev-asm-network\lib\util\utils.js:303:9)
    at E:\4486\11-June-2015\azure-xplat-cli-dev-asm-network\lib\util\logging.js:281:7
    at handleRedirect (E:\4486\11-June-2015\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\lib\services\filters\redirectfilter.js:36:9)
    at E:\4486\11-June-2015\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\lib\services\filters\errorhandlingfilter.js:49:7
    at Request._callback (E:\4486\11-June-2015\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\lib\http\request-pipeline.js:109:14)
    at Request.self.callback (E:\4486\11-June-2015\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\node_modules\request\request.js:199:22)
    at Request.emit (events.js:110:17)

error:   network gateway vnet shared-key set command failed</pre></code>

**Comment by roman-boltunov** [comment]
@HimanshuBri for now what I see is that request body is not generated correctly, could you please provide a screenshot of -vv output?

**Comment by HimanshuBri** [comment]
@roman-boltunov. Screenshot for -vv output.
![image](https://cloud.githubusercontent.com/assets/10084788/8107751/3f0bbe46-1069-11e5-8097-8efaeb367055.png)

**Comment by HimanshuBri** [comment]
@roman-boltunov. vnet and local network screenshot.
![image](https://cloud.githubusercontent.com/assets/10084788/8107787/7e796b28-1069-11e5-943e-b198d165d325.png)

**Comment by roman-boltunov** [comment]
@HimanshuBri can you try to set shared key for virtual network that associated with local network? Can you also try to set shared key for virtual network that already have gateway? Please share the results.

**Comment by HimanshuBri** [comment]
@roman-boltunov. Is it any specific key. how can we fetch it?

**Comment by roman-boltunov** [comment]
@HimanshuBri you can specify whatever you want for the key. For example 'set shared-key vnet -k "abcd" -t "testlocnet" ' must work.

**Comment by roman-boltunov** [comment]
@HimanshuBri actually we can set shared key only for virtual networks that have gateway.

**Comment by HimanshuBri** [comment]
@roman-boltunov. I hope this is fine.
![image](https://cloud.githubusercontent.com/assets/10084788/8108052/af9d80c0-106b-11e5-8138-c0da59f316c9.png)

**Comment by roman-boltunov** [comment]
@HimanshuBri this is completely strange. But I think anyway, according to server response we can mark it as external as it is not clear enough what's actually goes wrong.
Adding @anuchandy to confirm this is external.

**Comment by roman-boltunov** [comment]
@HimanshuBri one more thing, could you please also show 'vnet1' and 'testlocnet'?

**Comment by HimanshuBri** [comment]
@roman-boltunov. Is this fine.
![image](https://cloud.githubusercontent.com/assets/10084788/8108698/b00cc652-106f-11e5-9510-93060c0b33c5.png)

**Comment by roman-boltunov** [comment]
@HimanshuBri yes, looks like you did not associated virtual network with local network, that throws an error.

**Comment by HimanshuBri** [comment]
@roman-boltunov. Its working after associating virtual network with local network, but how can we see this shared-key

**Comment by roman-boltunov** [comment]
@HimanshuBri do you ask how can we look at the shared key after using 'set' command?

**Comment by HimanshuBri** [comment]
@roman-boltunov. yes

**Comment by roman-boltunov** [comment]
@HimanshuBri when we use 'set' command, we specify this key using '--key-value' parameter. For now it is not possible to show shared key through CLI. You can find this shared key on Azure portal only.

**Comment by HimanshuBri** [comment]
@roman-boltunov.Ok. Thanks for the information.

**Comment by roman-boltunov** [comment]
@anuchandy, according to @HimanshuBri comment - https://github.com/MSOpenTech/azure-xplat-cli/issues/322#issuecomment-111410185, this issue is also external. Please confirm.

**Comment by anuchandy** [comment]
This is external,  shared key reset works only if vnet is associated with a local network.
