### ISSUE TITLE
ASM: 'network gateway vnet shared-key reset' not working

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#322]
Please check code snippet.
<code><pre>
E:\4486\11-June-2015\azure-xplat-cli-dev-asm-network>node bin/azure network gateway vnet shared-key reset vnet 123 -t testlocnet -vv
info:    Executing command network gateway vnet shared-key reset
verbose: Resetting shared key for vnet "vnet"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'PUT',
silly:       headers: {
silly:           Content-Type: 'application/xml',
silly:           x-ms-version: '2014-10-01',
silly:           Content-Length: 164,
silly:           user-agent: 'WindowsAzureXplatCLI/0.9.2'
silly:       },
silly:       url: 'https://management.core.windows.net/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/services/networking/vnet/gateway/connection/testlocnet/sharedkey',
silly:       body: '<?xml version="1.0" encoding="utf-8" standalone="yes"?><ResetSharedKey xmlns="http://schemas.microsoft.com/windowsazure"><KeyLength>123</KeyLength></ResetSharedKey>'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 202,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           content-length: '210',
silly:           content-type: 'application/xml; charset=utf-8',
silly:           server: '1.0.6198.240 (rd_rdfe_stable.150608-1900) Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0',
silly:           x-ms-servedbyregion: 'usnorth2',
silly:           x-ms-request-id: 'cf2b7ada9dbaa8d2a7e6b3df66828ddd',
silly:           date: 'Thu, 11 Jun 2015 12:52:39 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: '<GatewayOperationAsyncResponse xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><ID>b0aaaaad-5511-4e17-a2fe-8d301934d07e</ID></GatewayOperationAsyncResponse>'
silly:   }
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { x-ms-version: '2014-10-01', user-agent: 'WindowsAzureXplatCLI/0.9.2' },
silly:       url: 'https://management.core.windows.net/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/services/networking/operation/b0aaaaad-5511-4e17-a2fe-8d301934d07e'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 200,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           content-length: '550',
silly:           content-type: 'application/xml; charset=utf-8',
silly:           server: '1.0.6198.240 (rd_rdfe_stable.150608-1900) Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0',
silly:           x-ms-servedbyregion: 'usnorth2',
silly:           x-ms-request-id: '87fe819d731cae6ab9db71217d4a1247',
silly:           date: 'Thu, 11 Jun 2015 12:53:11 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: '<GatewayOperation xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Data/><Error><Code>InternalError</Code><Message>An internal error has occurred.</Message></Error><HttpStatusCode>InternalServerError</HttpStatusCode><ID>b0aaaaad-5511-4e17-a2fe-8d301934d07e</ID><OperationCompletedTime>2015-06-11T12:52:40.7824735</OperationCompletedTime><OperationName>ResetSharedKey</OperationName><OperationStartedTime>2015-06-11T12:52:39.14
55073</OperationStartedTime><Status>Failed</Status></GatewayOperation>'
silly:   }
error:   InternalError : An internal error has occurred.
silly:   {
silly:       stack: 'Error: InternalError : An internal error has occurred.\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\lib\\networkManagementClient.js:6584:30\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\lib\\networkManagementClient.js:6004:14\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\lib\\util\\utils.js:326:7\n    at handleRedirect (E:\\4486\\11-June-2015\\azure-xplat-c
li-dev-asm-network\\lib\\util\\utils.js:303:9)\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\lib\\util\\logging.js:281:7\n    at handleRedirect (E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\services\\filters\\redirectfilter.js:36:9)\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\services\\filters\\errorhandlingfilter.js:4
9:7\n    at Request._callback (E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\http\\request-pipeline.js:109:14)\n    at Request.self.callback (E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\node_modules\\request\\request.js:199:22)\n    at Request.emit (events.js:110:17)\n',
silly:       message: 'InternalError : An internal error has occurred.',
silly:       error: { stack: 'Error: An internal error has occurred.\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\lib\\networkManagementClient.js:6585:32\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\lib\\networkManagementClient.js:6004:14\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\lib\\util\\utils.js:326:7\n    at handleRedirect (E:\\4486\\11-June-2015\\azure-xplat-cli-dev-
asm-network\\lib\\util\\utils.js:303:9)\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\lib\\util\\logging.js:281:7\n    at handleRedirect (E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\services\\filters\\redirectfilter.js:36:9)\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\services\\filters\\errorhandlingfilter.js:49:7\n
  at Request._callback (E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\http\\request-pipeline.js:109:14)\n    at Request.self.callback (E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\node_modules\\request\\request.js:199:22)\n    at Request.emit (events.js:110:17)\n', code: 'InternalError', message: 'An internal error has occurred.' },
silly:       __frame: {
silly:           name: 'resetSharedKey__11',
silly:           line: 230,
silly:           file: 'E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\lib\\commands\\asm\\network\\vpnGateway._js',
silly:           prev: {
silly:               name: 'resetSharedKey__42',
silly:               line: 282,
silly:               file: 'E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\lib\\commands\\asm\\network\\networkClient._js',
silly:               prev: {
silly:                   name: '__35',
silly:                   line: 679,
silly:                   file: 'E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\lib\\commands\\asm\\network._js',
silly:                   prev: undefined,
silly:                   calls: 3,
silly:                   active: false,
silly:                   offset: 5,
silly:                   col: 20
silly:               },
silly:               calls: 1,
silly:               active: false,
silly:               offset: 4,
silly:               col: 15
silly:           },
silly:           calls: 1,
silly:           active: false,
silly:           offset: 7,
silly:           col: 44
silly:       },
silly:       rawStack: 'Error: InternalError : An internal error has occurred.\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\lib\\networkManagementClient.js:6584:30\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\lib\\networkManagementClient.js:6004:14\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\lib\\util\\utils.js:326:7\n    at handleRedirect (E:\\4486\\11-June-2015\\azure-xpla
t-cli-dev-asm-network\\lib\\util\\utils.js:303:9)\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\lib\\util\\logging.js:281:7\n    at handleRedirect (E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\services\\filters\\redirectfilter.js:36:9)\n    at E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\services\\filters\\errorhandlingfilter.j
s:49:7\n    at Request._callback (E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\http\\request-pipeline.js:109:14)\n    at Request.self.callback (E:\\4486\\11-June-2015\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\node_modules\\request\\request.js:199:22)\n    at Request.emit (events.js:110:17)\n'
silly:   }
info:    Error information has been recorded to C:\Users\himanshu.agarwal\.azure\azure.err
verbose: Error: InternalError : An internal error has occurred.
    at E:\4486\11-June-2015\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\lib\networkManagementClient.js:6584:30
    at E:\4486\11-June-2015\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\lib\networkManagementClient.js:6004:14
    at E:\4486\11-June-2015\azure-xplat-cli-dev-asm-network\lib\util\utils.js:326:7
    at handleRedirect (E:\4486\11-June-2015\azure-xplat-cli-dev-asm-network\lib\util\utils.js:303:9)
    at E:\4486\11-June-2015\azure-xplat-cli-dev-asm-network\lib\util\logging.js:281:7
    at handleRedirect (E:\4486\11-June-2015\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\lib\services\filters\redirectfilter.js:36:9)
    at E:\4486\11-June-2015\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\lib\services\filters\errorhandlingfilter.js:49:7
    at Request._callback (E:\4486\11-June-2015\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\lib\http\request-pipeline.js:109:14)
    at Request.self.callback (E:\4486\11-June-2015\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\node_modules\request\request.js:199:22)
    at Request.emit (events.js:110:17)

error:   network gateway vnet shared-key reset command failed
</pre</code>

**Comment by roman-boltunov** [comment]
Adding @anuchandy. Please refer to #320 as it looks the same. Can we mark it as external as well?

**Comment by anuchandy** [comment]
If reset is failing due to not associated virtual network with local network, then it is external. Please confirm.

**Comment by HimanshuBri** [comment]
@anuchandy @roman-boltunov. Reset also working only after associating virtual network with local network.

**Comment by roman-boltunov** [comment]
@HimanshuBri thank you for verifying.
@anuchandy looks like it is external. Please confirm.

**Comment by anuchandy** [comment]
yes as we discussed above this is external since reset is failing due to not associated virtual network with local network

**Comment by roman-boltunov** [comment]
@anuchandy thank you for confirming.
