### ISSUE TITLE
ASM:  network application-gateway ssl-cert add command giving wrong error

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#335]
ASM network application-gateway ssl-cert add command giving wrong error 
<pre>
<code>
C:\Jun2015\15-Jun\azure-xplat-cli-dev-asm-network>node bin/azure network application-gateway ssl-cert add Testappgate sslCert -t C:\myCert.pem -p Brillio@2015
info:    Executing command network application-gateway ssl-cert add
+ Adding SSL certificate "sslCert" to application gateway "Testappgate"
error:   object is not a function
info:    Error information has been recorded to C:\Users\sreekanth.bandaru\.azure\azure.err
</code>
</pre>

<pre>
<code>C:\Jun2015\15-Jun\azure-xplat-cli-dev-asm-network>node bin/azure network application-gateway ssl-cert add Testappgate sslCert -t C:\myCert.pem -p Brillio@2015 -
vv
info:    Executing command network application-gateway ssl-cert add
verbose: Adding SSL certificate "sslCert" to application gateway "Testappgate"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'PUT',
silly:       headers: {
silly:           Content-Type: 'application/xml',
silly:           x-ms-version: '2014-10-01',
silly:           Content-Length: 2160,
silly:           user-agent: 'WindowsAzureXplatCLI/0.9.2'
silly:       },
silly:       url: 'https://management.core.windows.net/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/services/appgwprodnext/ApplicationGateways/Testappgate/sslcertificat
es/sslCert?api-version=1.0',
silly:       body: '<?xml version="1.0" encoding="utf-8" standalone="yes"?><CertificateFile xmlns="http://schemas.microsoft.com/windowsazure"><Data>LS0tLS1CRUdJ
TiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQvekNDQXVlZ0F3SUJBZ0lKQU1VQWErWFZMdkFlTUEwR0NTcUdTSWIzRFFFQkJRVUFNSUdWTVFzd0NRWUQKVlFRR0V3SkpiakVTTUJBR0ExVUVDQXdKUzJGeWJtRjBZV3Ro
TVJJd0VBWURWUVFIREFsQ1lXNW5ZV3h2Y21VeApFREFPQmdOVkJBb01CMkp5YVd4c2FXOHhFakFRQmdOVkJBc01DVzFwWTNKdmMyOW1kREVRTUE0R0ExVUVBd3dIClluSnBiR3hwYnpFbU1DUUdDU3FHU0liM0RR
RUpBUllYYzNKbFpXdGhiblJvWW5OQWVXRm9iMjh1WTI4dWFXNHcKSGhjTk1UVXdNekExTVRFMU16RXlXaGNOTVRZd016QTBNVEUxTXpFeVdqQ0JsVEVMTUFrR0ExVUVCaE1DU1c0eApFakFRQmdOVkJBZ01DVXRo
Y201aGRHRnJZVEVTTUJBR0ExVUVCd3dKUW1GdVoyRnNiM0psTVJBd0RnWURWUVFLCkRBZGljbWxzYkdsdk1SSXdFQVlEVlFRTERBbHRhV055YjNOdlpuUXhFREFPQmdOVkJBTU1CMkp5YVd4c2FXOHgKSmpBa0Jn
a3Foa2lHOXcwQkNRRVdGM055WldWcllXNTBhR0p6UUhsaGFHOXZMbU52TG1sdU1JSUJJakFOQmdrcQpoa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXlVTkthT3VUME5LK1M4Q2s4MXp5OXhKNmhYZlp2
QUM2CmxoYm1mLzZzL1dWaW1KL1RYNU5NaFFKd0M5azZaSUY5MktmWXJvakhOdkhEdWZTWjNFdEtVVndSRkNEam1nTVQKREwwOVdrR2FadDdnUk9ZRkswaVo0S3JZR292VXdsd3VtOWZIQjI0T0ppT1Y0YmkwZWs2
Mi9ySHg5ZmpZWnB2cAphSUgyUFYvaE44U0NaMHg3SEpNYmVyRDRnVm9VL0t2NDJuTnZ3akxVVzZJWmZWeC9HdjVPZUZEdFdIZlN2VUVGCmRhZEhLVFBuM0FiMjBJdTZnWkliTE85VnVmMzgvSXBhWUdmbkZDb3VI
ZHptaVRpTGllWU5lM0NVUGNPSk5TdjcKMUc4S1lweDN1TkpSa0pQYWI1T3NSeUp3NzVHdnprcjlPZ2FQc3M5dFZENkd0Njh1M1dRdFZRSURBUUFCbzFBdwpUakFkQmdOVkhRNEVGZ1FVb2d2aFhCK3haMkpKUGZM
TzZjVnM0Rm9yenNjd0h3WURWUjBqQkJnd0ZvQVVvZ3ZoClhCK3haMkpKUGZMTzZjVnM0Rm9yenNjd0RBWURWUjBUQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFVRkFBT0MKQVFFQWREajdxVU5KNDV4bEY1Y2pk
KzR4NU5IdkFEMVZUak9LdStYaC91elNTalhxQjJGMGFPTVdBOWx4MHFhUQpvSmdIa0d4ajN6ei9XN2lrL2NWR0wyTyt2UklPS3YveTBPUG9nRW1TM0h3K1ArTzZPR0U3eDFHNllOMHpMVm9MCnU0Qk4vQkVZbWp0
dHhNOUk3cXFMN0M1Y0pvRStLM3MvdzEvcHQvNjhvaEpjcjdGOU9oaTdjc282Mnh1R1kxUm0Ka3NBaDJFVURzVTlKVi9QK0M5QU1wTFNyYjAzSkpZelZqNHcxUkhicm13MkFqRnlHWGRRWWtnZ3lYaXNnK0lmcgo1
Z2JOTjdIaWdwSGY3YjJpM0NRQlVxcDltMjNmcmg1QWhuTEkycXAzVVhnYzUyVTVpZUxkaS90NmowVFRacXFZCkhoSHFvZktyajkzOEhIbEJOcEM1L0xWaDN3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
</Data><CertificateFormat>pem</CertificateFormat><Password>Brillio@2015</Password></CertificateFile>'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 400,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           content-length: '192',
silly:           content-type: 'application/xml; charset=utf-8',
silly:           server: '1.0.6198.240 (rd_rdfe_stable.150608-1900) Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0',
silly:           x-ms-servedbyregion: 'usnorth2',
silly:           x-ms-request-id: '55e2b94562feb9a4ad271885196ac38b',
silly:           date: 'Mon, 15 Jun 2015 12:53:24 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: '<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>BadRequest</Code><Message
>Only pfx certificates are allowed</Message></Error>'
silly:   }
error:   object is not a function
verbose: stack TypeError: object is not a function
    at C:\Jun2015\15-Jun\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\lib\networkManagementClient.js:321:16
    at C:\Jun2015\15-Jun\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\lib\networkManagementClient.js:476:16
    at C:\Jun2015\15-Jun\azure-xplat-cli-dev-asm-network\lib\util\utils.js:326:7
    at handleRedirect (C:\Jun2015\15-Jun\azure-xplat-cli-dev-asm-network\lib\util\utils.js:303:9)
    at C:\Jun2015\15-Jun\azure-xplat-cli-dev-asm-network\lib\util\logging.js:281:7
    at handleRedirect (C:\Jun2015\15-Jun\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\lib\services\filters\redirectfil
ter.js:36:9)
    at C:\Jun2015\15-Jun\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\lib\services\filters\errorhandlingfilter.js:49:7

    at Request._callback (C:\Jun2015\15-Jun\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\lib\http\request-pipeline.js:
109:14)
    at Request.self.callback (C:\Jun2015\15-Jun\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\node_modules\request\requ
est.js:199:22)
    at Request.emit (events.js:110:17)

silly:   { stack: 'TypeError: object is not a function\n    at C:\\Jun2015\\15-Jun\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\lib\\network
ManagementClient.js:321:16\n    at C:\\Jun2015\\15-Jun\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\lib\\networkManagementClient.js:476:16\n
    at C:\\Jun2015\\15-Jun\\azure-xplat-cli-dev-asm-network\\lib\\util\\utils.js:326:7\n    at handleRedirect (C:\\Jun2015\\15-Jun\\azure-xplat-cli-dev-asm-netw
ork\\lib\\util\\utils.js:303:9)\n    at C:\\Jun2015\\15-Jun\\azure-xplat-cli-dev-asm-network\\lib\\util\\logging.js:281:7\n    at handleRedirect (C:\\Jun2015\\1
5-Jun\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\services\\filters\\redirectfilter.js:36:9)\n    at C:\\J
un2015\\15-Jun\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\services\\filters\\errorhandlingfilter.js:49:7\
n    at Request._callback (C:\\Jun2015\\15-Jun\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-common\\lib\\http\\request-p
ipeline.js:109:14)\n    at Request.self.callback (C:\\Jun2015\\15-Jun\\azure-xplat-cli-dev-asm-network\\node_modules\\azure-mgmt-vnet\\node_modules\\azure-commo
n\\node_modules\\request\\request.js:199:22)\n    at Request.emit (events.js:110:17)\n', message: 'object is not a function' }
info:    Error information has been recorded to C:\Users\sreekanth.bandaru\.azure\azure.err
</code>
</pre>

**Comment by roman-boltunov** [comment]
@sreekanthbs hi, this is a known issue. It's already reported, let's wait for news about it.

**Comment by romangromov** [comment]
UPD: issue still exist on server side, this is a SDK issue

**Comment by bingosummer** [comment]
@romangromov Any update on this? This issue still exists in my test.
The issue blocks create an application gateway with ssl-offload. Any workaround?
Thanks

**Comment by bingosummer** [comment]
@romangromov Any update on this? Is it fixed?
In my test, even if I wanted to add a pfx certificate, the command still gave me a error.
```
azureuser@XXX:~$ azure network application-gateway ssl-cert add -n XXX -c sslcert -t /home/azureuser/certificate.pfx -p XXX
info:    Executing command network application-gateway ssl-cert add
+ Adding SSL certificate "sslcert" to Application Gateway "XXX"
error:   object is not a function
info:    Error information has been recorded to /home/azureuser/.azure/azure.err
```
However, we can see that the ssl certificate has been added successfully from the response.
```
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { x-ms-version: '2015-04-01' },
silly:       url: 'https://management.core.windows.net/XXX/services/networking/operation/XXX'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 200,
silly:       header: {
silly:           content-type: 'application/xml; charset=utf-8',
silly:           content-length: '400',
silly:           server: '1.0.6198.287 (rd_rdfe_stable.151030-2057) Microsoft-HTTPAPI/2.0',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           x-ms-request-id: 'XXX',
silly:           date: 'Sun, 22 Nov 2015 09:54:23 GMT',
silly:           x-ms-servedbyregion: 'ussouth3',
silly:           cache-control: 'no-cache'
silly:       },
silly:       body: '<GatewayOperation xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Data/><HttpStatusCode>OK</HttpStatusCode><ID>XXX</ID><OperationCompletedTime>2015-11-22T09:53:53.8909052</OperationCompletedTime><OperationStartedTime>2015-11-22T09:53:52.407656</OperationStartedTime><Status>Successful</Status></GatewayOperation>'
silly:   }
error:   object is not a function
verbose: stack TypeError: object is not a function
```
