### ISSUE TITLE
ARM: network vnet list with empty resource group throws error

### ISSUE THREAD

**Issue by babumuralidharan** [MSOpenTech/azure-xplat-cli#345]
Do an azure network vnet list
Cmd run will prompt for resource group name
Just hit enter without mentioning resource group name.
 command fails with api invalid error. 

This is pretty much common error for all list commands. This might be a regression.

We will have to fix this in sprint 50 branch as this issue should be fixed in the upcoming sprint.

__Verbose output below:__

```
$ node bin/azure network vnet list --verbose
info:    Executing command network vnet list
Resource group name:
verbose: Listing virtual networks
error:   The api-version '2015-05-01-preview' is invalid. The supported versions are '2015-01-01,2014-04-01-preview,2014-04-0
1,2014-01-01,2013-03-01,2014-02-26,2014-04'.
info:    Error information has been recorded to c:\Users\v-bamura\.azure\azure.err
verbose: Error: The api-version '2015-05-01-preview' is invalid. The supported versions are '2015-01-01,2014-04-01-preview,20
14-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
  <<< async stack >>>
  at list__5 (c:\InteropProjects\XPlat-Cli\ARM\myrepo\June17\azure-xplat-cli\lib\commands\arm\network\vnet._js:176:66)
  at listVNet__3 (c:\InteropProjects\XPlat-Cli\ARM\myrepo\June17\azure-xplat-cli\lib\commands\arm\network\networkClient._js:5
8:10)
  at __3 (c:\InteropProjects\XPlat-Cli\ARM\myrepo\June17\azure-xplat-cli\lib\commands\arm\network\network._js:91:21)
  <<< raw stack >>>
    at Function.ServiceClient._normalizeError (c:\InteropProjects\XPlat-Cli\ARM\myrepo\June17\azure-xplat-cli\node_modules\az
ure-common\lib\services\serviceclient.js:815:23)
    at c:\InteropProjects\XPlat-Cli\ARM\myrepo\June17\azure-xplat-cli\node_modules\azure-common\lib\services\filters\errorhan
dlingfilter.js:44:29
    at Request._callback (c:\InteropProjects\XPlat-Cli\ARM\myrepo\June17\azure-xplat-cli\node_modules\azure-common\lib\http\r
equest-pipeline.js:109:14)
    at Request.self.callback (c:\InteropProjects\XPlat-Cli\ARM\myrepo\June17\azure-xplat-cli\node_modules\azure-common\node_m
odules\request\request.js:199:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (c:\InteropProjects\XPlat-Cli\ARM\myrepo\June17\azure-xplat-cli\node_modules\azure-common\node_mod
ules\request\request.js:1160:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (c:\InteropProjects\XPlat-Cli\ARM\myrepo\June17\azure-xplat-cli\node_modules\azure-common\
node_modules\request\request.js:1111:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16

error:   network vnet list command failed

```

**Comment by babumuralidharan** [comment]
Closing this as we are triaging this issue in azure repo
