### ISSUE TITLE
ARM: network dns zone import with wrong dns-name giving error

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#538]
<pre>
<code>
C:\Oct2015\26oct\azure-xplat-cli-dev-arm-dns-import>node bin/azure network dns zone import --resource-group armresgrpdnszone --name example.com32 --file-name C:
\Oct2015\merge1.txt --force --verbose
info:    Executing command network dns zone import
warn:    The record set with fully-qualified name "example.com." does not match the zone name "example.com32.", skipped
warn:    The record set with fully-qualified name "test-a.example.com." does not match the zone name "example.com32.", skipped
warn:    The record set with fully-qualified name "test-aaaa.example.com." does not match the zone name "example.com32.", skipped
warn:    The record set with fully-qualified name "test-cname.example.com." does not match the zone name "example.com32.", skipped
warn:    The record set with fully-qualified name "test-mx.example.com." does not match the zone name "example.com32.", skipped
warn:    The record set with fully-qualified name "test-ns.example.com." does not match the zone name "example.com32.", skipped
warn:    The record set with fully-qualified name "_sip._tcp.test-srv.example.com." does not match the zone name "example.com32.", skipped
warn:    The record set with fully-qualified name "test-txt.example.com." does not match the zone name "example.com32.", skipped
warn:    The record set with fully-qualified name "test-a2.example.com." does not match the zone name "example.com32.", skipped
error:   Cannot read property 'toLowerCase' of undefined
info:    Error information has been recorded to C:\Users\sreekanth.bandaru\.azure\azure.err
verbose: TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.exports.stringEndsWith (C:\Oct2015\26oct\azure-xplat-cli-dev-arm-dns-import\lib\util\utils.js:724:16)
    at ZoneFile.__.extend.convertToFQDN (C:\Oct2015\26oct\azure-xplat-cli-dev-arm-dns-import\lib\commands\arm\network\zoneFile._js:268:15)
    at ZoneFile.__.extend.parseRR (C:\Oct2015\26oct\azure-xplat-cli-dev-arm-dns-import\lib\commands\arm\network\zoneFile._js:244:25)
    at ZoneFile.__.extend.parseRRs (C:\Oct2015\26oct\azure-xplat-cli-dev-arm-dns-import\lib\commands\arm\network\zoneFile._js:78:27)
    at ZoneFile.__.extend.parse (C:\Oct2015\26oct\azure-xplat-cli-dev-arm-dns-import\lib\commands\arm\network\zoneFile._js:30:17)
    at __$import__8 (C:\Oct2015\26oct\azure-xplat-cli-dev-arm-dns-import\lib\commands\arm\network\dnsZone._js:427:29)
    at __func (C:\Oct2015\26oct\azure-xplat-cli-dev-arm-dns-import\node_modules\streamline\lib\callbacks\runtime.js:47:5)
    at DnsZone.import__8 [as import] (C:\Oct2015\26oct\azure-xplat-cli-dev-arm-dns-import\lib\commands\arm\network\dnsZone._js:419:12)
    at ___ (C:\Oct2015\26oct\azure-xplat-cli-dev-arm-dns-import\lib\commands\arm\network\network._js:1447:34)
    at ___ (C:\Oct2015\26oct\azure-xplat-cli-dev-arm-dns-import\node_modules\streamline\lib\callbacks\runtime.js:111:13)

error:   network dns zone import command failed
</code>
</pre>

**Comment by romangromov** [comment]
@sreekanthbs please do not forget to attach zone file used

**Comment by sreekanthbs** [comment]
; This zone file assumes the zone name is 'example.com'
$ORIGIN example.com.

; Note, first record must be SOA.
@ IN SOA ns1.example.com. hostmaster (
                        2003080800 ; se = serial number
                        12h        ; ref = refresh
                        15m        ; ret = update retry
                        3w         ; ex = expiry
                        3h         ; min = minimum
                        )

; Create record set of each type
test-a IN A 1.2.3.4
test-aaaa IN AAAA 2001:cafe:130::100
test-cname IN CNAME target.com.
test-mx IN MX 10 mail.com.
test-ns IN NS ns1.com.
_sip._tcp.test-srv IN SRV 1 2 3 target.com.
test-txt IN TXT "string 1"	; Note, text is enclosed in quotes

; Create record set with multiple records
test-a2 IN A 1.2.3.4
		IN A 2.3.4.5

test-aaaa2 IN AAAA 2001:cafe:130::100
		   IN AAAA 2001:cafe:130::101

test-mx2 IN MX 10 mail.com.
		 IN MX 10 mail2.com.

test-ns2 IN NS ns1.com.
	 	IN NS ns2.com.

_sip._tcp.test-srv2 IN SRV 1 2 3 target.com.
			        IN SRV 1 2 3 target2.com.
				
test-txt2 IN TXT "string 1"
		  IN TXT "string 2"

		  
conflict-a IN A 1.2.3.4
conflict-cname IN CNAME test2.com.
conflict-ca IN CNAME gottherefirst.com.

**Comment by romangromov** [comment]
@sreekanthbs should be fixed now

**Comment by romangromov** [comment]
@sreekanthbs please verify or close, thanks

**Comment by sreekanthbs** [comment]
@romangromov  Verified and it is working fine, hence closing the issue
